### ISSUE TITLE
not working fedora 42

### ISSUE THREAD

**Issue by mjavadad** [bepass-org/oblivion-desktop#942]
### Attention | توجه

- [x] I searched and no similar issues were found | جستجو کردم و هیچ گزارش مشابهی پیدا نشد

### What Happened? | چه اتفاقی افتاده؟

mjavad@Fedora:~$ oblivion-desktop 
20:59:45.868 › Creating new od instance...
(node:5379) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `oblivion-desktop --trace-deprecation ...` to show where the warning was created)

(process:5379): Gtk-ERROR **: 20:59:45.902: GTK 2/3 symbols detected. Using GTK 2/3 and GTK 4 in the same process is not supported
Trace/breakpoint trap (core dumped)

### Relevant log output | لاگ برنامه

```shell
باز نشد
```

**Comment by AghaReza-RezaJaan** [comment]
Same problem on Kali.
I was not able to update the application after version 90 because of this problem

**Comment by 13matin37** [comment]
Update the app to the latest version (currently v2.97.0). Run the app from shell using `sudo oblivion-desktop --no-sandbox`. In case of facing any OpenGL-related error use `sudo oblivion-desktop --no-sandbox --disable-gpu-sandbox` instead. This issue was addressed before in #930 and #937 . For any further information follow [this wiki](https://github.com/bepass-org/oblivion-desktop/wiki/How-to-Fix-Blank-Screen-and-OpenGL-Error).

**Comment by AghaReza-RezaJaan** [comment]
I tried both of the commands but I'm still getting the same error message.

**Comment by ircfspace** [comment]
The cause of the issue is explained in this issue:
https://github.com/bepass-org/oblivion-desktop/wiki/How-to-Fix-Blank-Screen-and-OpenGL-Error

If the mentioned commands don’t work, you’ll need to either update your graphics card driver or wait for the next Electron update.

**Comment by ircfspace** [comment]
Electron had a recent update a few hours ago, and we updated our app accordingly.
Could you please check and see if the issue is resolved now?

https://github.com/bepass-org/oblivion-desktop/releases

**Comment by AghaReza-RezaJaan** [comment]
I upgraded to v2.97.4, but the issue persists.

Thanks for your efforts anyway.

![Image](https://github.com/user-attachments/assets/c22626ad-a7c7-495e-b890-4b69ab7ecd7a)
